#!/bin/bash

cd $(dirname $0)
venv=$(mktemp -d)

python -m venv $venv
source $venv/bin/activate
python -m pip install -r requirements.txt

python validate-config-profile.py "$@"
EC=$?

rm -rf $venv
exit $EC
