#!/bin/sh
# If Microsoft Defender for Endpoint is installed, then get MDE definitions date

if [ -f "/usr/local/bin/mdatp" ]; then
    result=`sudo mdatp health --field definitions_updated`
    dateresult=`date -j -f "%b %d, %Y at %H:%M:%S %p" "$result" +"%Y-%m-%d"`
    echo "<result>$dateresult</result>"
else
    echo "<result>Not Installed</result>"
fi
